type User = {
  email: string
  codeId: string
  status: string
  firstname: string
  lastname: string
  companyName: string
  address1: string
  address2: string
  datecreated: string
  country: string
  phonenumber: string
  notes: string
  company: number
  credit: number
  taxexempt: string
  latefeeoveride: number
  overideautosusp: string
  taxrateoverride: string
  taxrate: string
  cardtype: string
  cardnum: string
  expdate: string
  overideduenotices: boolean
  disableemails: string
  client_id: number
  currency_id: number
  affiliate_id: null
  group_name: string
  group_color: string
  billing_contact_id: number
  cardcreated: string
  cardupdated: string
  countryname: string
  assigned_affiliate: boolean
  achtype: string
  achaccount: string
  achrouting: string
  access: never[]
  socketId: never[]
  verified: boolean
  _2fa: boolean
  secret: string
  isHasSecret: boolean
  pwd: string
  national: string
  city: string
  district: string
  postCode: string
  currency: string
  address: string
  apiTokenTelegram: string
  from: string
  createdAt: string
  updatedAt: string
  accesstoken: string
  refreshtoken: string
  id: string
}

export type { User }
